

services:

  backend:
    image: web-service-backend
    build: ./example-backend
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://127.0.0.1:5000
      - REDIS_HOST=redisdb

  frontend:
    image: web-service-frontend
    build: ./example-frontend
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://127.0.0.1:8080

  redisdb:
    image: redis
